-- Database Schema for CA Practice Suite
-- This file contains SQL declarations for tables, constraints, and Row-Level Security (RLS) policies.

-- 1. Profiles Table (Assumed pre-existing, included for query context)
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, -- Maps to auth.uid()
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Employee', 'HR', 'Partner')),
  division TEXT CHECK (division IN ('Audit & Assurance Services', 'Other Professional Services')),
  onboarding_status TEXT NOT NULL CHECK (onboarding_status IN ('Pending Approval', 'Approved', 'Rejected')),
  monthly_salary NUMERIC(12, 2) DEFAULT 0.00,
  hourly_rate NUMERIC(10, 2) DEFAULT 0.00,
  joined_date DATE,
  leave_balance_casual INTEGER DEFAULT 6,
  leave_balance_sick INTEGER DEFAULT 6,
  leave_balance_earned INTEGER DEFAULT 12,
  two_factor_enabled BOOLEAN DEFAULT FALSE
);

-- 2. Audit Log Table (Tamper-proof)
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id TEXT NOT NULL,
  actor_role TEXT NOT NULL CHECK (actor_role IN ('HR', 'Partner', 'Employee')),
  action TEXT NOT NULL CHECK (action IN ('Created', 'Updated', 'Deleted', 'Finalized', 'Unlocked')),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('attendance', 'salary', 'assignment', 'employee', 'payroll')),
  entity_id TEXT NOT NULL,
  old_value JSONB,
  new_value JSONB,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  ip_address TEXT
);

-- Enable RLS for Audit Log
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

-- Select Policy: Only HR and Partner roles can select audit logs
CREATE POLICY select_audit_log ON audit_log
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('HR', 'Partner')
    )
  );

-- Insert Policy: Authenticated users can insert audit logs
CREATE POLICY insert_audit_log ON audit_log
  FOR INSERT
  TO authenticated
  WITH CHECK (TRUE);

-- Note: No UPDATE or DELETE policies are created.
-- In Supabase, this means UPDATE and DELETE requests will be denied to all app users.


-- 3. Cloud Archive Log Table (Tamper-proof)
CREATE TABLE IF NOT EXISTS archive_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('google_drive', 'dropbox')),
  files_uploaded INTEGER NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Success', 'Failed')),
  error_message TEXT,
  run_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Archive Log
ALTER TABLE archive_log ENABLE ROW LEVEL SECURITY;

-- Select Policy: Only HR and Partners can read archive logs
CREATE POLICY select_archive_log ON archive_log
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('HR', 'Partner')
    )
  );

-- Insert Policy: Only HR and Partners can insert archive logs
CREATE POLICY insert_archive_log ON archive_log
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('HR', 'Partner')
    )
  );

-- Note: No UPDATE or DELETE policies are created, blocking modifications.


-- 4. Client Master Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT,
  gstin TEXT,
  engagement_type TEXT
);

-- 5. Reusable Assignment Templates Table
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT
);

-- 6. Timesheets Table (Permanent storage of daily logged hours)
CREATE TABLE IF NOT EXISTS timesheets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  assignment_id BIGINT NOT NULL,
  date DATE NOT NULL,
  hours NUMERIC(4, 2) NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Settings Table Update (Add assignment types array column)
-- ALTER TABLE settings ADD COLUMN IF NOT EXISTS assignment_types JSONB DEFAULT '["Statutory Audit", "GST Monthly Return", "Tax Advisory"]'::jsonb;

-- 8. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'info',
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Notifications
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Select Policy: Users can only see their own notifications, unless HR/Partner
CREATE POLICY select_notifications ON notifications
  FOR SELECT
  TO authenticated
  USING (
    employee_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('HR', 'Partner')
    )
  );

-- Insert Policy: Users can insert notifications
CREATE POLICY insert_notifications ON notifications
  FOR INSERT
  TO authenticated
  WITH CHECK (TRUE);

-- 9. Supabase Storage Buckets & Policies for DPDP Act compliance
-- Create the attendance-selfies bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('attendance-selfies', 'attendance-selfies', false)
ON CONFLICT (id) DO NOTHING;

-- RLS policies for storage objects in attendance-selfies bucket
-- Allow authenticated employees to upload selfies (insert objects)
CREATE POLICY "Allow employees to upload selfies" ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'attendance-selfies'
    AND (storage.foldername(name))[1] = auth.uid()
  );

-- Allow only HR and Partner to read/download selfies (select objects)
CREATE POLICY "Allow HR and Partners to view selfies" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'attendance-selfies'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE public.profiles.id = auth.uid()
      AND public.profiles.role IN ('HR', 'Partner')
    )
  );

-- Allow employees to read/view their own selfies
CREATE POLICY "Allow employees to view own selfies" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'attendance-selfies'
    AND (storage.foldername(name))[1] = auth.uid()
  );
